// src/backend/config/permissions.js
// Mapa central de permisos por rol - VERSIÓN COMPLETA (sincronizada con frontend)

export const PERMISSIONS = Object.freeze({
  // Documentos
  VIEW_DOCUMENTS: 'viewDocuments',
  DOWNLOAD_DOCUMENTS: 'downloadDocuments',
  UPLOAD_DOCUMENTS: 'uploadDocuments',
  EDIT_DOCUMENTS: 'editDocuments',
  DELETE_DOCUMENTS: 'deleteDocuments',
  APPROVE_DOCUMENTS: 'approveDocuments',
  
  // Personas
  VIEW_PERSONS: 'viewPersons',
  CREATE_PERSON: 'createPerson',
  EDIT_PERSON: 'editPerson',
  DELETE_PERSON: 'deletePerson',
  
  // Categorías
  VIEW_CATEGORIES: 'viewCategories',
  CREATE_CATEGORY: 'createCategory',
  EDIT_CATEGORY: 'editCategory',
  DELETE_CATEGORY: 'deleteCategory',
  
  // Departamentos
  VIEW_DEPARTMENTS: 'viewDepartments',
  CREATE_DEPARTMENT: 'createDepartment',
  EDIT_DEPARTMENT: 'editDepartment',
  DELETE_DEPARTMENT: 'deleteDepartment',
  
  // Tareas
  VIEW_TASKS: 'viewTasks',
  CREATE_TASK: 'createTask',
  EDIT_TASK: 'editTask',
  DELETE_TASK: 'deleteTask',
  COMPLETE_TASK: 'completeTask',
  
  // Reportes
  VIEW_REPORTS: 'viewReports',
  GENERATE_REPORTS: 'generateReports',
  EXPORT_REPORTS: 'exportReports',
  
  // Administración
  MANAGE_USERS: 'manageUsers',
  VIEW_AUDIT_LOGS: 'viewAuditLogs',
  VIEW_SYSTEM_SETTINGS: 'viewSystemSettings',
  EDIT_SYSTEM_SETTINGS: 'editSystemSettings',
  
  // Papelera
  VIEW_TRASH: 'viewTrash',
  RESTORE_FROM_TRASH: 'restoreFromTrash',
  EMPTY_TRASH: 'emptyTrash',
  
  // Calendario
  VIEW_CALENDAR: 'viewCalendar',
  CREATE_EVENT: 'createEvent',
  EDIT_EVENT: 'editEvent',
  DELETE_EVENT: 'deleteEvent',
  
  // Historial
  VIEW_HISTORY: 'viewHistory',
  EXPORT_HISTORY: 'exportHistory',
  CLEAR_HISTORY: 'clearHistory',
  
  // Soporte
  VIEW_SUPPORT: 'viewSupport',
  CREATE_TICKET: 'createTicket',
  VIEW_ALL_TICKETS: 'viewAllTickets',
  RESPOND_TICKET: 'respondTicket',
  CLOSE_TICKET: 'closeTicket'
});

export const ROLES = Object.freeze({
  ADMIN: 'administrador',
  GERENTE: 'gerente',
  SUPERVISOR: 'supervisor',
  EDITOR: 'editor',
  REVISOR: 'revisor',
  LECTOR: 'lector',
  MODERADOR: 'moderador',
  USUARIO: 'usuario',
  DISABLED: 'desactivado'
});

export const ROLE_PERMISSIONS = Object.freeze({
  // ADMIN - Control total
  [ROLES.ADMIN]: [
    // Documentos
    PERMISSIONS.VIEW_DOCUMENTS,
    PERMISSIONS.DOWNLOAD_DOCUMENTS,
    PERMISSIONS.UPLOAD_DOCUMENTS,
    PERMISSIONS.EDIT_DOCUMENTS,
    PERMISSIONS.DELETE_DOCUMENTS,
    PERMISSIONS.APPROVE_DOCUMENTS,
    
    // Personas
    PERMISSIONS.VIEW_PERSONS,
    PERMISSIONS.CREATE_PERSON,
    PERMISSIONS.EDIT_PERSON,
    PERMISSIONS.DELETE_PERSON,
    
    // Categorías
    PERMISSIONS.VIEW_CATEGORIES,
    PERMISSIONS.CREATE_CATEGORY,
    PERMISSIONS.EDIT_CATEGORY,
    PERMISSIONS.DELETE_CATEGORY,
    
    // Departamentos
    PERMISSIONS.VIEW_DEPARTMENTS,
    PERMISSIONS.CREATE_DEPARTMENT,
    PERMISSIONS.EDIT_DEPARTMENT,
    PERMISSIONS.DELETE_DEPARTMENT,
    
    // Tareas
    PERMISSIONS.VIEW_TASKS,
    PERMISSIONS.CREATE_TASK,
    PERMISSIONS.EDIT_TASK,
    PERMISSIONS.DELETE_TASK,
    PERMISSIONS.COMPLETE_TASK,
    
    // Reportes
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.GENERATE_REPORTS,
    PERMISSIONS.EXPORT_REPORTS,
    
    // Administración
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.VIEW_AUDIT_LOGS,
    PERMISSIONS.VIEW_SYSTEM_SETTINGS,
    PERMISSIONS.EDIT_SYSTEM_SETTINGS,
    
    // Papelera
    PERMISSIONS.VIEW_TRASH,
    PERMISSIONS.RESTORE_FROM_TRASH,
    PERMISSIONS.EMPTY_TRASH,
    
    // Calendario
    PERMISSIONS.VIEW_CALENDAR,
    PERMISSIONS.CREATE_EVENT,
    PERMISSIONS.EDIT_EVENT,
    PERMISSIONS.DELETE_EVENT,
    
    // Historial
    PERMISSIONS.VIEW_HISTORY,
    PERMISSIONS.EXPORT_HISTORY,
    PERMISSIONS.CLEAR_HISTORY,
    
    // Soporte
    PERMISSIONS.VIEW_SUPPORT,
    PERMISSIONS.CREATE_TICKET,
    PERMISSIONS.VIEW_ALL_TICKETS,
    PERMISSIONS.RESPOND_TICKET,
    PERMISSIONS.CLOSE_TICKET
  ],

  // GERENTE - Gestión completa excepto admin
  [ROLES.GERENTE]: [
    PERMISSIONS.VIEW_DOCUMENTS,
    PERMISSIONS.DOWNLOAD_DOCUMENTS,
    PERMISSIONS.UPLOAD_DOCUMENTS,
    PERMISSIONS.EDIT_DOCUMENTS,
    PERMISSIONS.DELETE_DOCUMENTS,
    PERMISSIONS.APPROVE_DOCUMENTS,
    PERMISSIONS.VIEW_PERSONS,
    PERMISSIONS.CREATE_PERSON,
    PERMISSIONS.EDIT_PERSON,
    PERMISSIONS.DELETE_PERSON,
    PERMISSIONS.VIEW_CATEGORIES,
    PERMISSIONS.CREATE_CATEGORY,
    PERMISSIONS.EDIT_CATEGORY,
    PERMISSIONS.DELETE_CATEGORY,
    PERMISSIONS.VIEW_DEPARTMENTS,
    PERMISSIONS.CREATE_DEPARTMENT,
    PERMISSIONS.EDIT_DEPARTMENT,
    PERMISSIONS.DELETE_DEPARTMENT,
    PERMISSIONS.VIEW_TASKS,
    PERMISSIONS.CREATE_TASK,
    PERMISSIONS.EDIT_TASK,
    PERMISSIONS.DELETE_TASK,
    PERMISSIONS.COMPLETE_TASK,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.GENERATE_REPORTS,
    PERMISSIONS.EXPORT_REPORTS,
    PERMISSIONS.VIEW_TRASH,
    PERMISSIONS.RESTORE_FROM_TRASH,
    PERMISSIONS.VIEW_CALENDAR,
    PERMISSIONS.CREATE_EVENT,
    PERMISSIONS.EDIT_EVENT,
    PERMISSIONS.DELETE_EVENT,
    PERMISSIONS.VIEW_HISTORY,
    PERMISSIONS.VIEW_SUPPORT,
    PERMISSIONS.CREATE_TICKET,
    PERMISSIONS.VIEW_ALL_TICKETS
  ],

  // SUPERVISOR
  [ROLES.SUPERVISOR]: [
    PERMISSIONS.VIEW_DOCUMENTS,
    PERMISSIONS.DOWNLOAD_DOCUMENTS,
    PERMISSIONS.APPROVE_DOCUMENTS,
    PERMISSIONS.VIEW_PERSONS,
    PERMISSIONS.VIEW_CATEGORIES,
    PERMISSIONS.VIEW_DEPARTMENTS,
    PERMISSIONS.VIEW_TASKS,
    PERMISSIONS.COMPLETE_TASK,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.GENERATE_REPORTS,
    PERMISSIONS.EXPORT_REPORTS,
    PERMISSIONS.VIEW_TRASH,
    PERMISSIONS.VIEW_CALENDAR,
    PERMISSIONS.VIEW_HISTORY,
    PERMISSIONS.VIEW_SUPPORT,
    PERMISSIONS.CREATE_TICKET
  ],

  // EDITOR
  [ROLES.EDITOR]: [
    PERMISSIONS.VIEW_DOCUMENTS,
    PERMISSIONS.DOWNLOAD_DOCUMENTS,
    PERMISSIONS.UPLOAD_DOCUMENTS,
    PERMISSIONS.EDIT_DOCUMENTS,
    PERMISSIONS.VIEW_PERSONS,
    PERMISSIONS.CREATE_PERSON,
    PERMISSIONS.EDIT_PERSON,
    PERMISSIONS.VIEW_CATEGORIES,
    PERMISSIONS.CREATE_CATEGORY,
    PERMISSIONS.EDIT_CATEGORY,
    PERMISSIONS.VIEW_DEPARTMENTS,
    PERMISSIONS.VIEW_TASKS,
    PERMISSIONS.CREATE_TASK,
    PERMISSIONS.EDIT_TASK,
    PERMISSIONS.COMPLETE_TASK,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_CALENDAR,
    PERMISSIONS.CREATE_EVENT,
    PERMISSIONS.EDIT_EVENT,
    PERMISSIONS.VIEW_SUPPORT,
    PERMISSIONS.CREATE_TICKET
  ],

  // REVISOR
  [ROLES.REVISOR]: [
    PERMISSIONS.VIEW_DOCUMENTS,
    PERMISSIONS.DOWNLOAD_DOCUMENTS,
    PERMISSIONS.APPROVE_DOCUMENTS,
    PERMISSIONS.VIEW_PERSONS,
    PERMISSIONS.VIEW_CATEGORIES,
    PERMISSIONS.VIEW_DEPARTMENTS,
    PERMISSIONS.VIEW_TASKS,
    PERMISSIONS.COMPLETE_TASK,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_CALENDAR,
    PERMISSIONS.VIEW_SUPPORT
  ],

  // LECTOR
  [ROLES.LECTOR]: [
    PERMISSIONS.VIEW_DOCUMENTS,
    PERMISSIONS.DOWNLOAD_DOCUMENTS,
    PERMISSIONS.VIEW_PERSONS,
    PERMISSIONS.VIEW_CATEGORIES,
    PERMISSIONS.VIEW_DEPARTMENTS,
    PERMISSIONS.VIEW_TASKS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_CALENDAR,
    PERMISSIONS.VIEW_SUPPORT
  ],

  // MODERADOR (compatibilidad)
  [ROLES.MODERADOR]: [
    PERMISSIONS.VIEW_DOCUMENTS,
    PERMISSIONS.DOWNLOAD_DOCUMENTS,
    PERMISSIONS.UPLOAD_DOCUMENTS,
    PERMISSIONS.EDIT_DOCUMENTS,
    PERMISSIONS.DELETE_DOCUMENTS,
    PERMISSIONS.APPROVE_DOCUMENTS,
    PERMISSIONS.VIEW_PERSONS,
    PERMISSIONS.CREATE_PERSON,
    PERMISSIONS.EDIT_PERSON,
    PERMISSIONS.VIEW_CATEGORIES,
    PERMISSIONS.VIEW_DEPARTMENTS,
    PERMISSIONS.VIEW_TASKS,
    PERMISSIONS.CREATE_TASK,
    PERMISSIONS.COMPLETE_TASK,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_TRASH,
    PERMISSIONS.VIEW_CALENDAR,
    PERMISSIONS.VIEW_SUPPORT,
    PERMISSIONS.CREATE_TICKET
  ],

  // USUARIO (compatibilidad)
  [ROLES.USUARIO]: [
    PERMISSIONS.VIEW_DOCUMENTS,
    PERMISSIONS.DOWNLOAD_DOCUMENTS,
    PERMISSIONS.VIEW_PERSONS,
    PERMISSIONS.VIEW_CATEGORIES,
    PERMISSIONS.VIEW_DEPARTMENTS,
    PERMISSIONS.VIEW_TASKS,
    PERMISSIONS.VIEW_CALENDAR,
    PERMISSIONS.VIEW_SUPPORT
  ],

  [ROLES.DISABLED]: []
});

export function getRolePermissions(role) {
  return ROLE_PERMISSIONS[role] || [];
}

export function hasPermission(role, permission) {
  const perms = getRolePermissions(role);
  return perms.includes(permission);
}

export function hasAnyPermission(role, permissions = []) {
  const perms = getRolePermissions(role);
  return permissions.some((p) => perms.includes(p));
}