// =============================================================================
// src/frontend/modules/documentos/core/MultipleUploadState.js
// =============================================================================

import { CONFIG } from '../../../config.js';
import { formatFileSize, showAlert } from '../../../utils.js';

/**
 * Clase que gestiona el estado completo de la subida múltiple de archivos.
 * Controla archivos pendientes, en progreso, completados y fallidos,
 * así como configuraciones comunes para todos los archivos.
 */
export class MultipleUploadState {
    constructor() {
        console.log('🆕 [MultipleUploadState] Constructor - Creando nueva instancia');
        this.reset();
    }

    /**
     * Reinicia completamente el estado de subida múltiple.
     * Útil para comenzar una nueva sesión de subida.
     */
    reset() {
        console.log('🔄 [MultipleUploadState] Reset - Reiniciando estado completo');
        this.files = [];
        this.currentUploads = [];
        this.completedUploads = [];
        this.failedUploads = [];
        this.isUploading = false;
        this.totalSize = 0;
        this.commonCategory = '';
        this.commonPersonId = '';
        this.expirationDays = null;
        this.uploadStrategy = 'sequential';
        this.autoGenerateDescriptions = true;
        this.notifyPerson = false;
        this.notifyExpiration = true;
        
        console.log('✅ [MultipleUploadState] Reset completado:', {
            filesCount: 0,
            commonCategory: '(vacío)',
            commonPersonId: '(vacío)',
            expirationDays: null,
            totalSize: '0 bytes'
        });
    }

    /**
     * Agrega nuevos archivos al estado, validando cada uno individualmente.
     * Evita duplicados y aplica validaciones de tipo y tamaño.
     * @param {File[]} newFiles - Array de archivos a agregar
     * @returns {number} - Cantidad de archivos agregados
     */
    addFiles(newFiles) {
        console.group('📦 [MultipleUploadState] addFiles');
        console.log('📁 Archivos recibidos para agregar:', newFiles.length);
        
        // Mostrar estado actual antes de agregar
        console.log('📊 Estado ACTUAL antes de agregar:', {
            totalArchivos: this.files.length,
            commonCategory: `"${this.commonCategory}"`,
            commonPersonId: `"${this.commonPersonId}"`,
            expirationDays: this.expirationDays,
            totalSize: formatFileSize(this.totalSize)
        });
        
        let addedCount = 0;
        
        for (const file of newFiles) {
            // Verificar si ya existe
            const existingFile = this.files.find(f => 
                f.file.name === file.name && 
                f.file.size === file.size &&
                f.file.lastModified === file.lastModified
            );
            
            if (!existingFile) {
                // Validar archivo individual
                if (this.validateSingleFile(file)) {
                    const fileObj = this.createFileObject(file);
                    this.files.push(fileObj);
                    this.totalSize += file.size;
                    addedCount++;
                    
                    console.log(`✅ Archivo AGREGADO: ${file.name}`, {
                        size: formatFileSize(file.size),
                        id: fileObj.id,
                        customCategory: fileObj.customCategory || '(vacía - usará común)',
                        customPersonId: fileObj.customPersonId || '(vacía - usará común)',
                        customExpirationDate: fileObj.customExpirationDate || '(sin fecha - usará común)',
                        status: fileObj.status
                    });
                }
            } else {
                console.log(`⚠️ Archivo DUPLICADO ignorado: ${file.name}`);
            }
        }
        
        // Mostrar estado después de agregar
        console.log(`📊 Resumen de operación addFiles:`);
        console.log(`   • Archivos recibidos: ${newFiles.length}`);
        console.log(`   • Archivos agregados: ${addedCount}`);
        console.log(`   • Duplicados ignorados: ${newFiles.length - addedCount}`);
        console.log(`   • Total archivos ahora: ${this.files.length}`);
        console.log(`   • Tamaño total ahora: ${formatFileSize(this.totalSize)}`);
        
        // Mostrar detalles de configuración actual
        console.log('🔧 Configuración actual aplicada:');
        console.log(`   • Categoría común: "${this.commonCategory || '(no establecida)'}"`);
        console.log(`   • Persona común: "${this.commonPersonId || '(no establecida)'}"`);
        console.log(`   • Días de expiración: ${this.expirationDays !== null ? `${this.expirationDays} días` : 'no establecido'}`);
        
        // Si hay archivos, mostrar detalles de cada uno
        if (this.files.length > 0) {
            console.log('📋 Detalle de archivos en estado:');
            this.files.forEach((f, i) => {
                const effectiveCategory = this.getEffectiveCategory(f);
                const effectivePersonId = this.getEffectivePersonId(f);
                const effectiveExpirationDate = this.getEffectiveExpirationDate(f);
                
                console.log(`${i + 1}. ${f.file.name}`, {
                    status: f.status,
                    categoría: effectiveCategory || '(ERROR: sin categoría)',
                    persona: effectivePersonId || '(sin persona)',
                    vencimiento: effectiveExpirationDate || '(sin fecha)',
                    tamaño: formatFileSize(f.file.size)
                });
            });
        }
        
        console.groupEnd();
        return addedCount;
    }

    /**
     * Crea un objeto de archivo con todas las propiedades necesarias
     * @param {File} file - Archivo a procesar
     * @returns {object} - Objeto de archivo completo
     */
    createFileObject(file) {
        console.log(`📄 [MultipleUploadState] createFileObject para: ${file.name}`);
        
        const fileObj = {
            file: file,
            id: this.generateFileId(file),
            status: 'pending',
            progress: 0,
            error: null,
            description: file.name.replace(/\.[^/.]+$/, ""), // Nombre sin extensión
            customCategory: '',
            customPersonId: '',
            customExpirationDate: null,
            addedAt: new Date().toISOString(),
            uploadedAt: null,
            retryCount: 0
        };
        
        console.log(`📝 Valores por defecto para ${file.name}:`, {
            customCategory: '(vacío)',
            customPersonId: '(vacío)',
            customExpirationDate: 'null'
        });
        
        // IMPORTANTE: Asignar valores comunes si existen
        // Esto asegura que los archivos tengan valores desde el principio
        
        // 1. Asignar categoría común si existe
        if (this.commonCategory && this.commonCategory.trim() !== '') {
            fileObj.customCategory = this.commonCategory;
            console.log(`🏷️ Asignando categoría común "${this.commonCategory}" a: ${file.name}`);
        } else {
            console.log(`🏷️ NO hay categoría común para asignar a: ${file.name}`);
        }
        
        // 2. Asignar persona común si existe
        if (this.commonPersonId && this.commonPersonId.trim() !== '') {
            fileObj.customPersonId = this.commonPersonId;
            console.log(`👤 Asignando persona común "${this.commonPersonId}" a: ${file.name}`);
        } else {
            console.log(`👤 NO hay persona común para asignar a: ${file.name}`);
        }
        
        // 3. Calcular y asignar fecha de expiración si hay días configurados
        if (this.expirationDays !== null && this.expirationDays > 0) {
            fileObj.customExpirationDate = this.calculateExpirationDate(this.expirationDays);
            console.log(`📅 Asignando fecha de vencimiento ${fileObj.customExpirationDate} a: ${file.name}`);
        } else {
            console.log(`📅 NO hay días de expiración para calcular fecha para: ${file.name}`);
        }
        
        return fileObj;
    }

    /**
     * Calcula una fecha de vencimiento basada en días
     * @param {number} days - Días a agregar
     * @returns {string} - Fecha en formato YYYY-MM-DD
     */
    calculateExpirationDate(days) {
        console.log(`📆 [MultipleUploadState] calculateExpirationDate: hoy + ${days} días`);
        
        const expirationDate = new Date();
        expirationDate.setDate(expirationDate.getDate() + days);
        const formattedDate = expirationDate.toISOString().split('T')[0];
        
        console.log(`📆 Fecha calculada: ${formattedDate}`);
        return formattedDate;
    }

    /**
     * Elimina un archivo del estado por su ID.
     * @param {string} fileId - ID único del archivo a eliminar
     * @returns {boolean} - True si se eliminó correctamente
     */
    removeFile(fileId) {
        console.log(`🗑️ [MultipleUploadState] removeFile - ID: ${fileId}`);
        
        const index = this.files.findIndex(f => f.id === fileId);
        if (index !== -1) {
            const removedFile = this.files[index];
            this.totalSize -= removedFile.file.size;
            this.files.splice(index, 1);
            
            console.log(`✅ Archivo REMOVIDO: ${removedFile.file.name}`, {
                tamañoRestado: formatFileSize(removedFile.file.size),
                totalArchivosRestantes: this.files.length,
                tamañoTotalAhora: formatFileSize(this.totalSize)
            });
            
            return true;
        }
        
        console.log(`❌ No se encontró archivo con ID: ${fileId}`);
        return false;
    }

    /**
     * Actualiza la categoría común y la aplica a todos los archivos pendientes
     * @param {string} category - Nueva categoría común
     */
    setCommonCategory(category) {
        console.group(`🏷️ [MultipleUploadState] setCommonCategory`);
        console.log(`📝 Valor recibido: "${category}"`);
        console.log(`📝 Valor anterior: "${this.commonCategory}"`);
        
        // Guardar nueva categoría
        const oldCategory = this.commonCategory;
        this.commonCategory = category ? category.trim() : '';
        
        console.log(`✅ Categoría común ACTUALIZADA: "${oldCategory}" → "${this.commonCategory}"`);
        
        // Aplicar a todos los archivos pendientes sin categoría personalizada
        let updatedCount = 0;
        this.files.forEach(file => {
            if (file.status === 'pending') {
                // Solo actualizar si no hay categoría personalizada
                if (!file.customCategory || file.customCategory.trim() === '') {
                    file.customCategory = this.commonCategory;
                    updatedCount++;
                    console.log(`🔄 Aplicada categoría común a: ${file.file.name}`);
                } else {
                    console.log(`⚠️ ${file.file.name} ya tiene categoría personalizada: "${file.customCategory}"`);
                }
            }
        });
        
        console.log(`📊 Resumen: ${updatedCount} archivo(s) actualizado(s) con categoría común`);
        
        // Verificación después de actualizar
        const categoryCheck = this.checkCategories();
        console.log(`🔍 Verificación POST-actualización:`, {
            totalArchivos: categoryCheck.totalFiles,
            conCategoría: categoryCheck.filesWithCategory,
            sinCategoría: categoryCheck.missingCategories
        });
        
        console.groupEnd();
    }

    /**
     * Actualiza la persona común y la aplica a todos los archivos pendientes
     * @param {string} personId - Nueva persona común
     */
    setCommonPersonId(personId) {
        console.group(`👤 [MultipleUploadState] setCommonPersonId`);
        console.log(`📝 Valor recibido: "${personId}"`);
        console.log(`📝 Valor anterior: "${this.commonPersonId}"`);
        
        // Guardar nueva persona
        const oldPersonId = this.commonPersonId;
        this.commonPersonId = personId ? personId.trim() : '';
        
        console.log(`✅ Persona común ACTUALIZADA: "${oldPersonId}" → "${this.commonPersonId}"`);
        
        // Aplicar a todos los archivos pendientes sin persona personalizada
        let updatedCount = 0;
        this.files.forEach(file => {
            if (file.status === 'pending') {
                // Solo actualizar si no hay persona personalizada
                if (!file.customPersonId || file.customPersonId.trim() === '') {
                    file.customPersonId = this.commonPersonId;
                    updatedCount++;
                    console.log(`🔄 Aplicada persona común a: ${file.file.name}`);
                } else {
                    console.log(`⚠️ ${file.file.name} ya tiene persona personalizada: "${file.customPersonId}"`);
                }
            }
        });
        
        console.log(`📊 Resumen: ${updatedCount} archivo(s) actualizado(s) con persona común`);
        
        // Verificación después de actualizar
        const filesWithPerson = this.files.filter(f => 
            this.getEffectivePersonId(f) && this.getEffectivePersonId(f).trim() !== ''
        ).length;
        console.log(`🔍 Verificación POST-actualización:`, {
            totalArchivos: this.files.length,
            conPersona: filesWithPerson,
            sinPersona: this.files.length - filesWithPerson
        });
        
        console.groupEnd();
    }

    /**
     * Actualiza los días de expiración y calcula fechas para todos los archivos pendientes
     * @param {number|string} days - Días hasta el vencimiento
     */
    setExpirationDays(days) {
        console.group(`📅 [MultipleUploadState] setExpirationDays`);
        console.log(`📝 Valor recibido: "${days}" (tipo: ${typeof days})`);
        console.log(`📝 Valor anterior: ${this.expirationDays}`);
        
        // Validar y convertir el valor
        const daysNumber = parseInt(days);
        
        if (isNaN(daysNumber) || daysNumber <= 0) {
            this.expirationDays = null;
            console.log('✅ Días de expiración establecidos como: null (sin vencimiento)');
            
            // Eliminar fechas de vencimiento de todos los archivos pendientes sin fecha personalizada
            let clearedCount = 0;
            this.files.forEach(file => {
                if (file.status === 'pending') {
                    if (!file.customExpirationDate) {
                        file.customExpirationDate = null;
                        clearedCount++;
                    }
                }
            });
            console.log(`🗑️ ${clearedCount} archivo(s) con fecha de vencimiento limpiada`);
            
        } else {
            this.expirationDays = daysNumber;
            console.log(`✅ Días de expiración establecidos: ${this.expirationDays} días`);
            
            // Calcular fecha de vencimiento
            const expirationDate = this.calculateExpirationDate(daysNumber);
            console.log(`📅 Fecha calculada para vencimiento: ${expirationDate}`);
            
            // Aplicar a todos los archivos pendientes sin fecha personalizada
            let updatedCount = 0;
            this.files.forEach(file => {
                if (file.status === 'pending') {
                    // Solo actualizar si no hay fecha personalizada
                    if (!file.customExpirationDate) {
                        file.customExpirationDate = expirationDate;
                        updatedCount++;
                        console.log(`🔄 Aplicada fecha de vencimiento a: ${file.file.name}`);
                    } else {
                        console.log(`⚠️ ${file.file.name} ya tiene fecha personalizada: "${file.customExpirationDate}"`);
                    }
                }
            });
            
            console.log(`📊 Resumen: ${updatedCount} archivo(s) actualizado(s) con fecha de vencimiento`);
        }
        
        // Verificación después de actualizar
        const filesWithDate = this.files.filter(f => 
            this.getEffectiveExpirationDate(f)
        ).length;
        console.log(`🔍 Verificación POST-actualización:`, {
            totalArchivos: this.files.length,
            conFechaVencimiento: filesWithDate,
            sinFechaVencimiento: this.files.length - filesWithDate
        });
        
        console.groupEnd();
    }

    /**
     * VALOR CRÍTICO: Aplica la configuración común a TODOS los archivos pendientes
     * Esto asegura que todos los archivos tengan los valores correctos antes de subir
     * @returns {number} - Número de archivos actualizados
     */
    applyCommonSettingsToAllFiles() {
        console.group('🔄 [MultipleUploadState] applyCommonSettingsToAllFiles');
        
        console.log('🔧 Configuración común actual:', {
            categoría: `"${this.commonCategory || '(vacía)'}"`,
            persona: `"${this.commonPersonId || '(vacía)'}"`,
            díasExpiración: this.expirationDays !== null ? `${this.expirationDays} días` : 'null'
        });
        
        let updatedFiles = 0;
        let skippedFiles = 0;
        
        this.files.forEach((file, index) => {
            if (file.status === 'pending') {
                let fileUpdated = false;
                
                console.log(`${index + 1}. Procesando: ${file.file.name}`, {
                    categoríaActual: file.customCategory || '(vacía)',
                    personaActual: file.customPersonId || '(vacía)',
                    fechaActual: file.customExpirationDate || '(sin fecha)'
                });
                
                // 1. Aplicar categoría común si no tiene personalizada
                if (this.commonCategory && this.commonCategory.trim() !== '') {
                    if (!file.customCategory || file.customCategory.trim() === '') {
                        file.customCategory = this.commonCategory;
                        fileUpdated = true;
                        console.log(`   🏷️ Categoría actualizada: "${this.commonCategory}"`);
                    } else {
                        console.log(`   ⚠️ Mantiene categoría personalizada: "${file.customCategory}"`);
                    }
                } else {
                    console.log(`   ❌ No hay categoría común para aplicar`);
                }
                
                // 2. Aplicar persona común si no tiene personalizada
                if (this.commonPersonId && this.commonPersonId.trim() !== '') {
                    if (!file.customPersonId || file.customPersonId.trim() === '') {
                        file.customPersonId = this.commonPersonId;
                        fileUpdated = true;
                        console.log(`   👤 Persona actualizada: "${this.commonPersonId}"`);
                    } else {
                        console.log(`   ⚠️ Mantiene persona personalizada: "${file.customPersonId}"`);
                    }
                } else {
                    console.log(`   ❌ No hay persona común para aplicar`);
                }
                
                // 3. Aplicar fecha de vencimiento si no tiene personalizada y hay días configurados
                if (this.expirationDays !== null && this.expirationDays > 0) {
                    if (!file.customExpirationDate) {
                        const expirationDate = this.calculateExpirationDate(this.expirationDays);
                        file.customExpirationDate = expirationDate;
                        fileUpdated = true;
                        console.log(`   📅 Fecha actualizada: ${expirationDate} (+${this.expirationDays} días)`);
                    } else {
                        console.log(`   ⚠️ Mantiene fecha personalizada: "${file.customExpirationDate}"`);
                    }
                } else {
                    console.log(`   ❌ No hay días de expiración para calcular fecha`);
                }
                
                if (fileUpdated) {
                    updatedFiles++;
                    console.log(`   ✅ Archivo ACTUALIZADO con configuración común`);
                } else {
                    skippedFiles++;
                    console.log(`   🔄 Archivo MANTENIDO (ya tiene configuración personalizada)`);
                }
                
                // Mostrar valores efectivos después de la aplicación
                console.log(`   📊 Valores efectivos después:`, {
                    categoría: this.getEffectiveCategory(file) || '(vacía)',
                    persona: this.getEffectivePersonId(file) || '(vacía)',
                    fecha: this.getEffectiveExpirationDate(file) || '(sin fecha)'
                });
            } else {
                console.log(`${index + 1}. ${file.file.name} - SKIP (estado: ${file.status})`);
            }
        });
        
        console.log('📊 RESUMEN:', {
            archivosTotales: this.files.length,
            archivosActualizados: updatedFiles,
            archivosMantenidos: skippedFiles,
            archivosConCategoría: this.files.filter(f => this.getEffectiveCategory(f)).length,
            archivosConPersona: this.files.filter(f => this.getEffectivePersonId(f)).length,
            archivosConFecha: this.files.filter(f => this.getEffectiveExpirationDate(f)).length
        });
        
        console.groupEnd();
        return updatedFiles;
    }

    /**
     * Valida un archivo individual según configuraciones del sistema.
     * Verifica tipo de archivo, tamaño individual y tamaño total acumulado.
     * @param {File} file - Archivo a validar
     * @returns {boolean} - True si el archivo es válido
     */
    validateSingleFile(file) {
        console.log(`🔍 [MultipleUploadState] validateSingleFile: ${file.name}`);
        
        try {
            // Validar tipo de archivo
            const fileExtension = file.name.split('.').pop().toLowerCase();
            if (!CONFIG.ALLOWED_FILE_TYPES.includes(fileExtension)) {
                console.error(`❌ Tipo NO PERMITIDO: ${fileExtension}`);
                console.error(`❌ Extensiones permitidas: ${CONFIG.ALLOWED_FILE_TYPES.join(', ')}`);
                showAlert(
                    `"${file.name}" - Tipo no permitido. Formatos aceptados: ${CONFIG.ALLOWED_FILE_TYPES.join(', ').toUpperCase()}`,
                    'error'
                );
                return false;
            }

            // Validar tamaño individual
            if (file.size > CONFIG.MAX_FILE_SIZE) {
                console.error(`❌ Tamaño EXCEDIDO: ${formatFileSize(file.size)} > ${formatFileSize(CONFIG.MAX_FILE_SIZE)}`);
                showAlert(
                    `"${file.name}" - Excede el tamaño máximo por archivo (${formatFileSize(CONFIG.MAX_FILE_SIZE)})`,
                    'error'
                );
                return false;
            }

            // Validar tamaño total (si ya hay archivos)
            if (this.totalSize + file.size > CONFIG.MAX_TOTAL_UPLOAD_SIZE) {
                console.error(`❌ Tamaño TOTAL excedido`);
                console.error(`❌ Actual: ${formatFileSize(this.totalSize)} + Nuevo: ${formatFileSize(file.size)} > Límite: ${formatFileSize(CONFIG.MAX_TOTAL_UPLOAD_SIZE)}`);
                showAlert(
                    `"${file.name}" - Excede el tamaño total permitido para múltiples archivos`,
                    'error'
                );
                return false;
            }

            console.log(`✅ Archivo VÁLIDO: ${file.name}`);
            return true;

        } catch (error) {
            console.error(`❌ ERROR validando archivo ${file.name}:`, error);
            showAlert(`Error validando "${file.name}": ${error.message}`, 'error');
            return false;
        }
    }

    /**
     * Valida todos los archivos en el estado globalmente.
     * Verifica límites, categorías y otros requisitos del sistema.
     * @returns {boolean} - True si todos los archivos son válidos
     */
    validateAllFiles() {
        console.group('🔍 [MultipleUploadState] VALIDACIÓN COMPLETA');
        
        const errors = [];
        
        // Mostrar estado actual para debugging
        console.log('📊 Estado ACTUAL para validación:', {
            totalArchivos: this.files.length,
            commonCategory: `"${this.commonCategory}"`,
            commonPersonId: `"${this.commonPersonId}"`,
            expirationDays: this.expirationDays,
            totalSize: formatFileSize(this.totalSize)
        });
        
        // 1. Verificar que haya archivos
        if (this.files.length === 0) {
            errors.push('No hay archivos seleccionados');
            console.error('❌ ERROR: No hay archivos para validar');
            console.groupEnd();
            return false;
        }

        // 2. Verificar límite de archivos
        if (this.files.length > CONFIG.MAX_MULTIPLE_FILES) {
            errors.push(`Máximo ${CONFIG.MAX_MULTIPLE_FILES} archivos permitidos. Tienes: ${this.files.length}`);
            console.error(`❌ ERROR: Límite de archivos excedido: ${this.files.length} > ${CONFIG.MAX_MULTIPLE_FILES}`);
        }

        // 3. Verificar tamaño total
        if (this.totalSize > CONFIG.MAX_TOTAL_UPLOAD_SIZE) {
            errors.push(`Tamaño total excedido (${formatFileSize(this.totalSize)} > ${formatFileSize(CONFIG.MAX_TOTAL_UPLOAD_SIZE)})`);
            console.error(`❌ ERROR: Tamaño total excedido: ${formatFileSize(this.totalSize)} > ${formatFileSize(CONFIG.MAX_TOTAL_UPLOAD_SIZE)}`);
        }

        // 4. VERIFICACIÓN DETALLADA DE CATEGORÍAS (CRÍTICO)
        console.log('🏷️ Verificando categorías...');
        const categoryCheck = this.checkCategories();
        console.log('📊 Resultado verificación categorías:', {
            totalArchivos: categoryCheck.totalFiles,
            conCategoría: categoryCheck.filesWithCategory,
            sinCategoría: categoryCheck.missingCategories,
            todosTienenCategoría: categoryCheck.allHaveCategory
        });
        
        if (!categoryCheck.allHaveCategory) {
            const errorMsg = `${categoryCheck.missingCategories} archivo(s) no tienen categoría asignada`;
            errors.push(errorMsg);
            console.error(`❌ ERROR: ${errorMsg}`);
            
            // Mostrar qué archivos no tienen categoría
            const filesWithoutCategory = categoryCheck.details.filter(d => !d.hasCategory);
            console.error('❌ Archivos SIN CATEGORÍA:', filesWithoutCategory.map(f => f.name));
            
            // Intentar asignar categoría común si existe
            if (this.commonCategory && this.commonCategory.trim() !== '') {
                console.log('🔄 Intentando asignar categoría común a archivos sin categoría...');
                let fixedCount = 0;
                this.files.forEach(file => {
                    const effectiveCategory = this.getEffectiveCategory(file);
                    if (!effectiveCategory || effectiveCategory.trim() === '') {
                        file.customCategory = this.commonCategory;
                        fixedCount++;
                        console.log(`✅ Asignada categoría común a: ${file.file.name}`);
                    }
                });
                
                if (fixedCount > 0) {
                    console.log(`✅ ${fixedCount} archivo(s) corregido(s) con categoría común`);
                    
                    // Re-verificar después de la corrección
                    const newCheck = this.checkCategories();
                    if (newCheck.allHaveCategory) {
                        console.log('✅ TODOS los archivos ahora tienen categoría');
                        // Remover el error si se corrigió
                        const errorIndex = errors.findIndex(e => e.includes('no tienen categoría'));
                        if (errorIndex !== -1) {
                            errors.splice(errorIndex, 1);
                            console.log('✅ Error de categorías corregido automáticamente');
                        }
                    } else {
                        console.error(`❌ Aún hay ${newCheck.missingCategories} archivos sin categoría`);
                    }
                }
            } else {
                console.error('❌ No hay categoría común para asignar');
            }
        }

        // 5. Verificar que todas las categorías sean válidas (no vacías)
        const invalidCategories = this.files.filter(f => {
            const cat = this.getEffectiveCategory(f);
            return !cat || cat.trim() === '';
        });
        
        if (invalidCategories.length > 0) {
            const errorMsg = `${invalidCategories.length} archivo(s) no tienen categoría válida`;
            errors.push(errorMsg);
            console.error(`❌ ERROR: ${errorMsg}`);
            console.error('❌ Archivos con categoría inválida:', invalidCategories.map(f => f.file.name));
        }

        // 6. Verificar fechas de vencimiento (solo formato, no obligatorio)
        const invalidDates = [];
        this.files.forEach(file => {
            const date = this.getEffectiveExpirationDate(file);
            if (date && date.trim() !== '') {
                const dateObj = new Date(date);
                if (isNaN(dateObj.getTime())) {
                    invalidDates.push(file.file.name);
                }
            }
        });
        
        if (invalidDates.length > 0) {
            const errorMsg = `${invalidDates.length} archivo(s) tienen fecha de vencimiento inválida`;
            errors.push(errorMsg);
            console.error(`❌ ERROR: ${errorMsg}`);
            console.error('❌ Archivos con fecha inválida:', invalidDates);
        }

        // 7. Resultado final de la validación
        if (errors.length > 0) {
            console.error('❌ ERRORES DE VALIDACIÓN ENCONTRADOS:', errors);
            console.log('📊 Estado FINAL para debugging:');
            this.logState();
            
            // Mostrar alertas al usuario
            errors.forEach(error => showAlert(error, 'error'));
            
            console.groupEnd();
            return false;
        }

        console.log('✅ VALIDACIÓN EXITOSA - Todos los archivos son válidos');
        console.log('📊 Resumen FINAL:', {
            totalArchivos: this.files.length,
            archivosConCategoria: categoryCheck.filesWithCategory,
            categoríaComún: this.commonCategory || '(no establecida)',
            personaComún: this.commonPersonId || '(no establecida)',
            díasExpiración: this.expirationDays !== null ? `${this.expirationDays} días` : '(no establecido)',
            tamañoTotal: formatFileSize(this.totalSize),
            estado: 'LISTO PARA SUBIR'
        });
        
        console.groupEnd();
        return true;
    }

    /**
     * Obtiene la categoría efectiva para un archivo específico.
     * Prioriza categoría personalizada sobre categoría común.
     * @param {object} fileObj - Objeto de archivo
     * @returns {string} - Categoría a usar
     */
    getEffectiveCategory(fileObj) {
        // Primero intenta usar la categoría personalizada
        if (fileObj.customCategory && fileObj.customCategory.trim() !== '') {
            return fileObj.customCategory.trim();
        }
        // Si no hay categoría personalizada, usa la común
        if (this.commonCategory && this.commonCategory.trim() !== '') {
            return this.commonCategory.trim();
        }
        // Si no hay ninguna, retorna vacío
        return '';
    }

    /**
     * Obtiene la persona efectiva para un archivo específico.
     * Prioriza persona personalizada sobre persona común.
     * @param {object} fileObj - Objeto de archivo
     * @returns {string} - Persona a usar
     */
    getEffectivePersonId(fileObj) {
        // Primero intenta usar la persona personalizada
        if (fileObj.customPersonId && fileObj.customPersonId.trim() !== '') {
            return fileObj.customPersonId.trim();
        }
        // Si no hay persona personalizada, usa la común
        if (this.commonPersonId && this.commonPersonId.trim() !== '') {
            return this.commonPersonId.trim();
        }
        // Si no hay ninguna, retorna vacío
        return '';
    }

    /**
     * Obtiene la fecha de vencimiento efectiva para un archivo específico.
     * @param {object} fileObj - Objeto de archivo
     * @returns {string|null} - Fecha de vencimiento o null
     */
    getEffectiveExpirationDate(fileObj) {
        // Primero intenta usar la fecha personalizada
        if (fileObj.customExpirationDate) {
            return fileObj.customExpirationDate;
        }
        // Si no hay fecha personalizada, calcula basada en días comunes
        if (this.expirationDays !== null && this.expirationDays !== undefined && this.expirationDays > 0) {
            return this.calculateExpirationDate(this.expirationDays);
        }
        // Si no hay configuración, retorna null
        return null;
    }

    /**
     * Prepara los datos de todos los archivos para enviar al servidor.
     * @returns {Array} - Array de objetos preparados para subida
     */
    prepareFilesForUpload() {
        console.group('📤 [MultipleUploadState] PREPARANDO ARCHIVOS PARA SUBIDA');
        
        const preparedFiles = this.files.map((fileObj, index) => {
            const effectiveCategory = this.getEffectiveCategory(fileObj);
            const effectivePersonId = this.getEffectivePersonId(fileObj);
            const effectiveExpirationDate = this.getEffectiveExpirationDate(fileObj);
            
            // VALIDACIÓN CRÍTICA: Asegurar que tenemos categoría
            if (!effectiveCategory || effectiveCategory.trim() === '') {
                console.error(`❌ ERROR CRÍTICO: ${fileObj.file.name} NO TIENE CATEGORÍA`);
                console.error(`   • customCategory: "${fileObj.customCategory}"`);
                console.error(`   • commonCategory: "${this.commonCategory}"`);
                console.error(`   • effectiveCategory: "${effectiveCategory}"`);
            }
            
            const preparedFile = {
                file: fileObj.file,
                fileName: fileObj.file.name,
                fileSize: fileObj.file.size,
                fileType: fileObj.file.type,
                description: fileObj.description || fileObj.file.name.replace(/\.[^/.]+$/, ""),
                category: effectiveCategory,
                personId: effectivePersonId,
                expirationDate: effectiveExpirationDate,
                notifyPerson: this.notifyPerson && effectivePersonId !== '',
                notifyExpiration: this.notifyExpiration && effectiveExpirationDate !== null,
                status: 'pending'
            };
            
            console.log(`${index + 1}. ${fileObj.file.name}`, {
                categoría: preparedFile.category || '(ERROR: vacía)',
                persona: preparedFile.personId || '(sin persona)',
                fechaVencimiento: preparedFile.expirationDate || '(sin fecha)',
                notificarPersona: preparedFile.notifyPerson,
                notificarVencimiento: preparedFile.notifyExpiration,
                tamaño: formatFileSize(preparedFile.fileSize)
            });
            
            return preparedFile;
        });
        
        console.log(`✅ ${preparedFiles.length} archivo(s) preparado(s) para subida`);
        
        // Verificación CRÍTICA: Asegurar que todos tengan categoría
        const filesWithoutCategory = preparedFiles.filter(f => !f.category || f.category.trim() === '');
        if (filesWithoutCategory.length > 0) {
            console.error('❌ ERROR CRÍTICO: Archivos sin categoría:', filesWithoutCategory.map(f => f.fileName));
            console.error('❌ Esto causará que la subida falle en el servidor');
            
            // Intentar corregir asignando categoría común
            if (this.commonCategory && this.commonCategory.trim() !== '') {
                console.log('🔄 Intentando corregir asignando categoría común...');
                filesWithoutCategory.forEach(f => {
                    f.category = this.commonCategory;
                    console.log(`✅ Corregido: ${f.fileName} → categoría: "${this.commonCategory}"`);
                });
                
                // Re-verificar
                const remaining = preparedFiles.filter(f => !f.category || f.category.trim() === '');
                if (remaining.length === 0) {
                    console.log('✅ Todos los archivos corregidos con categoría común');
                }
            }
            
            throw new Error(`${filesWithoutCategory.length} archivos no tienen categoría asignada`);
        }
        
        console.groupEnd();
        return preparedFiles;
    }

    /**
     * Genera un ID único para un archivo basado en nombre, tamaño y timestamp.
     * @param {File} file - Archivo para generar ID
     * @returns {string} - ID único del archivo
     */
    generateFileId(file) {
        const id = `file_${file.name}_${file.size}_${file.lastModified}_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
        return id;
    }

    /**
     * Actualiza el estado de un archivo específico
     * @param {string} fileId - ID del archivo
     * @param {object} updates - Actualizaciones a aplicar
     */
    updateFile(fileId, updates) {
        console.log(`📝 [MultipleUploadState] updateFile: ${fileId}`);
        
        const fileIndex = this.files.findIndex(f => f.id === fileId);
        if (fileIndex !== -1) {
            const oldStatus = this.files[fileIndex].status;
            this.files[fileIndex] = { ...this.files[fileIndex], ...updates };
            
            if (updates.status === 'completed') {
                this.files[fileIndex].uploadedAt = new Date().toISOString();
            }
            
            console.log(`✅ Archivo actualizado: ${this.files[fileIndex].file.name}`, {
                estadoAnterior: oldStatus,
                estadoNuevo: updates.status,
                cambios: Object.keys(updates)
            });
            
            return true;
        }
        
        console.log(`❌ No se encontró archivo con ID: ${fileId}`);
        return false;
    }

    /**
     * Limpia archivos según estado
     * @param {string} status - Estado de archivos a limpiar
     */
    cleanupFiles(status = null) {
        console.group(`🗑️ [MultipleUploadState] cleanupFiles`);
        console.log(`Estado a limpiar: ${status || 'todos'}`);
        console.log(`Archivos antes de limpiar: ${this.files.length}`);
        
        if (status) {
            const initialCount = this.files.length;
            this.files = this.files.filter(f => f.status !== status);
            const removedCount = initialCount - this.files.length;
            console.log(`✅ ${removedCount} archivo(s) limpiado(s) con estado: ${status}`);
        } else {
            this.files = [];
            console.log('✅ TODOS los archivos limpiados');
        }
        
        // Recalcular tamaño total
        this.totalSize = this.files.reduce((sum, f) => sum + f.file.size, 0);
        console.log(`📊 Archivos después de limpiar: ${this.files.length}`);
        console.log(`📊 Tamaño total después de limpiar: ${formatFileSize(this.totalSize)}`);
        
        console.groupEnd();
    }

    /**
     * Obtiene estadísticas actuales del estado de subida.
     * @returns {object} - Objeto con conteos de archivos por estado y tamaños
     */
    getStats() {
        const stats = {
            total: this.files.length,
            pending: this.files.filter(f => f.status === 'pending').length,
            uploading: this.files.filter(f => f.status === 'uploading').length,
            completed: this.files.filter(f => f.status === 'completed').length,
            failed: this.files.filter(f => f.status === 'failed').length,
            totalSize: this.totalSize,
            uploadedSize: this.files
                .filter(f => f.status === 'completed')
                .reduce((sum, f) => sum + f.file.size, 0)
        };
        
        console.log(`📈 [MultipleUploadState] getStats:`, stats);
        return stats;
    }

    /**
     * Verifica si todos los archivos tienen categoría
     * @returns {object} - Resultado de la verificación
     */
    checkCategories() {
        console.log(`🔍 [MultipleUploadState] checkCategories`);
        
        const details = this.files.map(f => {
            const effectiveCategory = this.getEffectiveCategory(f);
            const effectivePersonId = this.getEffectivePersonId(f);
            const effectiveExpirationDate = this.getEffectiveExpirationDate(f);
            
            return {
                name: f.file.name,
                hasCategory: !!(effectiveCategory && effectiveCategory.trim() !== ''),
                customCategory: f.customCategory || '(vacía)',
                effectiveCategory: effectiveCategory || '(sin categoría)',
                customPersonId: f.customPersonId || '(vacía)',
                effectivePersonId: effectivePersonId || '(sin persona)',
                customExpirationDate: f.customExpirationDate || '(sin fecha)',
                effectiveExpirationDate: effectiveExpirationDate || '(sin fecha)',
                status: f.status
            };
        });
        
        const filesWithCategory = details.filter(d => d.hasCategory).length;
        
        const result = {
            allHaveCategory: filesWithCategory === this.files.length,
            totalFiles: this.files.length,
            filesWithCategory: filesWithCategory,
            missingCategories: this.files.length - filesWithCategory,
            commonCategory: this.commonCategory,
            commonPersonId: this.commonPersonId,
            expirationDays: this.expirationDays,
            details: details
        };
        
        console.log(`📊 Resultado checkCategories:`, {
            todosTienenCategoría: result.allHaveCategory,
            conCategoría: result.filesWithCategory,
            sinCategoría: result.missingCategories
        });
        
        return result;
    }

    /**
     * Verifica si todos los archivos tienen persona asignada
     * @returns {object} - Resultado de la verificación
     */
    checkPersons() {
        console.log(`👤 [MultipleUploadState] checkPersons`);
        
        const details = this.files.map(f => {
            const effectivePersonId = this.getEffectivePersonId(f);
            
            return {
                name: f.file.name,
                hasPerson: !!(effectivePersonId && effectivePersonId.trim() !== ''),
                effectivePersonId: effectivePersonId || '(sin persona)',
                status: f.status
            };
        });
        
        const filesWithPerson = details.filter(d => d.hasPerson).length;
        
        const result = {
            allHavePerson: filesWithPerson === this.files.length,
            totalFiles: this.files.length,
            filesWithPerson: filesWithPerson,
            missingPersons: this.files.length - filesWithPerson,
            commonPersonId: this.commonPersonId
        };
        
        console.log(`📊 Resultado checkPersons:`, {
            todosTienenPersona: result.allHavePerson,
            conPersona: result.filesWithPerson,
            sinPersona: result.missingPersons
        });
        
        return result;
    }

    /**
     * Verifica si todos los archivos tienen fecha de vencimiento
     * @returns {object} - Resultado de la verificación
     */
    checkExpirations() {
        console.log(`📅 [MultipleUploadState] checkExpirations`);
        
        const details = this.files.map(f => {
            const effectiveExpirationDate = this.getEffectiveExpirationDate(f);
            
            return {
                name: f.file.name,
                hasExpiration: !!(effectiveExpirationDate),
                effectiveExpirationDate: effectiveExpirationDate || '(sin fecha)',
                status: f.status
            };
        });
        
        const filesWithExpiration = details.filter(d => d.hasExpiration).length;
        
        const result = {
            allHaveExpiration: filesWithExpiration === this.files.length,
            totalFiles: this.files.length,
            filesWithExpiration: filesWithExpiration,
            missingExpirations: this.files.length - filesWithExpiration,
            expirationDays: this.expirationDays
        };
        
        console.log(`📊 Resultado checkExpirations:`, {
            todosTienenVencimiento: result.allHaveExpiration,
            conVencimiento: result.filesWithExpiration,
            sinVencimiento: result.missingExpirations
        });
        
        return result;
    }

    /**
     * Muestra en consola el estado actual de la subida múltiple.
     * Útil para debugging y seguimiento de progreso.
     */
    logState() {
        console.group('📊 [MultipleUploadState] ESTADO COMPLETO');
        
        const stats = this.getStats();
        console.log('📈 ESTADÍSTICAS:');
        console.table({
            'Total Archivos': stats.total,
            'Pendientes': stats.pending,
            'Subiendo': stats.uploading,
            'Completados': stats.completed,
            'Fallidos': stats.failed,
            'Tamaño Total': formatFileSize(stats.totalSize),
            'Subido': formatFileSize(stats.uploadedSize)
        });
        
        console.log('🔧 CONFIGURACIÓN COMÚN:');
        console.log(`  • Categoría: "${this.commonCategory || '(NO ESTABLECIDA)'}"`);
        console.log(`  • Persona ID: "${this.commonPersonId || '(NO ESTABLECIDA)'}"`);
        console.log(`  • Días expiración: ${this.expirationDays !== null ? this.expirationDays + ' días' : '(NO ESTABLECIDO)'}`);
        console.log(`  • Estrategia: ${this.uploadStrategy}`);
        console.log(`  • Auto-descripciones: ${this.autoGenerateDescriptions ? 'Sí' : 'No'}`);
        console.log(`  • Notificar persona: ${this.notifyPerson ? 'Sí' : 'No'}`);
        
        if (this.files.length > 0) {
            console.log('📋 DETALLE POR ARCHIVO:');
            this.files.forEach((file, index) => {
                const effectiveCategory = this.getEffectiveCategory(file);
                const effectivePersonId = this.getEffectivePersonId(file);
                const effectiveExpirationDate = this.getEffectiveExpirationDate(file);
                
                console.log(`${index + 1}. ${file.file.name}`, {
                    status: file.status,
                    progress: file.status === 'uploading' ? `${file.progress}%` : 'N/A',
                    'categoría.personalizada': file.customCategory || '(vacía)',
                    'categoría.efectiva': effectiveCategory || '(ERROR: sin categoría)',
                    'persona.personalizada': file.customPersonId || '(vacía)',
                    'persona.efectiva': effectivePersonId || '(sin persona)',
                    'vencimiento.personalizado': file.customExpirationDate || '(sin fecha)',
                    'vencimiento.efectivo': effectiveExpirationDate || '(sin fecha)',
                    error: file.error || 'N/A',
                    tamaño: formatFileSize(file.file.size)
                });
            });
        } else {
            console.log('📋 DETALLE POR ARCHIVO: (No hay archivos)');
        }
        
        console.groupEnd();
    }

    /**
     * Obtiene archivos por estado
     * @param {string} status - Estado a filtrar
     * @returns {Array} - Archivos con ese estado
     */
    getFilesByStatus(status) {
        const files = this.files.filter(f => f.status === status);
        console.log(`📋 [MultipleUploadState] getFilesByStatus(${status}): ${files.length} archivo(s)`);
        return files;
    }

    /**
     * Obtiene el siguiente archivo pendiente para subir
     * @returns {object|null} - Siguiente archivo o null
     */
    getNextPendingFile() {
        const nextFile = this.files.find(f => f.status === 'pending') || null;
        console.log(`➡️ [MultipleUploadState] getNextPendingFile:`, nextFile ? nextFile.file.name : 'null');
        return nextFile;
    }

    /**
     * Verifica si hay archivos pendientes
     * @returns {boolean} - True si hay archivos pendientes
     */
    hasPendingFiles() {
        const hasPending = this.files.some(f => f.status === 'pending');
        console.log(`❓ [MultipleUploadState] hasPendingFiles: ${hasPending}`);
        return hasPending;
    }

    /**
     * Verifica si todos los archivos están completados
     * @returns {boolean} - True si todos están completados
     */
    allFilesCompleted() {
        const allCompleted = this.files.every(f => f.status === 'completed' || f.status === 'failed');
        console.log(`❓ [MultipleUploadState] allFilesCompleted: ${allCompleted}`);
        return allCompleted;
    }

    /**
     * DEPURACIÓN: Imprime información detallada de un archivo específico
     * @param {string} fileId - ID del archivo
     */
    debugFile(fileId) {
        console.group(`🐛 [MultipleUploadState] debugFile: ${fileId}`);
        
        const fileObj = this.files.find(f => f.id === fileId);
        if (fileObj) {
            console.log('📋 INFORMACIÓN DEL ARCHIVO:');
            console.log(`  • Nombre: ${fileObj.file.name}`);
            console.log(`  • Tamaño: ${formatFileSize(fileObj.file.size)}`);
            console.log(`  • Tipo: ${fileObj.file.type}`);
            console.log(`  • Status: ${fileObj.status}`);
            console.log(`  • Progreso: ${fileObj.progress}%`);
            console.log(`  • Error: ${fileObj.error || 'Ninguno'}`);
            
            console.log('🏷️ CONFIGURACIÓN:');
            console.log(`  • Categoría personalizada: "${fileObj.customCategory || '(vacía)'}"`);
            console.log(`  • Persona personalizada: "${fileObj.customPersonId || '(vacía)'}"`);
            console.log(`  • Fecha vencimiento personalizada: "${fileObj.customExpirationDate || '(sin fecha)'}"`);
            
            console.log('🔧 VALORES EFECTIVOS:');
            console.log(`  • Categoría efectiva: "${this.getEffectiveCategory(fileObj) || '(ERROR: vacía)'}"`);
            console.log(`  • Persona efectiva: "${this.getEffectivePersonId(fileObj) || '(sin persona)'}"`);
            console.log(`  • Fecha vencimiento efectiva: "${this.getEffectiveExpirationDate(fileObj) || '(sin fecha)'}"`);
            
            console.log('🌐 CONFIGURACIÓN COMÚN:');
            console.log(`  • Categoría común: "${this.commonCategory || '(no establecida)'}"`);
            console.log(`  • Persona común: "${this.commonPersonId || '(no establecida)'}"`);
            console.log(`  • Días expiración: ${this.expirationDays !== null ? this.expirationDays + ' días' : 'no establecido'}`);
        } else {
            console.log(`❌ No se encontró archivo con ID: ${fileId}`);
        }
        
        console.groupEnd();
    }
}