// =============================================================================
// src/frontend/modules/documentos/core/MultipleUploadState.js
// =============================================================================

import { CONFIG } from '../../../config.js';
import { formatFileSize, showAlert } from '../../../utils.js';

/**
 * Clase que gestiona el estado completo de la subida múltiple de archivos.
 * Controla archivos pendientes, en progreso, completados y fallidos,
 * así como configuraciones comunes para todos los archivos.
 */
export class MultipleUploadState {
    constructor() {
        console.log('🔄 Creando nueva instancia de MultipleUploadState');
        this.reset();
    }

    /**
     * Reinicia completamente el estado de subida múltiple.
     * Útil para comenzar una nueva sesión de subida.
     */
    reset() {
        console.log('🔄 Reseteando estado de subida múltiple');
        this.files = [];
        this.currentUploads = [];
        this.completedUploads = [];
        this.failedUploads = [];
        this.isUploading = false;
        this.totalSize = 0;
        this.commonCategory = '';
        this.commonPersonId = '';
        this.expirationDays = null;
        this.uploadStrategy = 'sequential';
        this.autoGenerateDescriptions = true;
        this.notifyPerson = false;
        
        console.log('✅ Estado reseteado:', {
            filesCount: this.files.length,
            commonCategory: this.commonCategory,
            totalSize: this.totalSize
        });
    }

    /**
     * Agrega nuevos archivos al estado, validando cada uno individualmente.
     * Evita duplicados y aplica validaciones de tipo y tamaño.
     * @param {File[]} newFiles - Array de archivos a agregar
     */
    addFiles(newFiles) {
        console.group('📦 Agregando archivos múltiples');
        console.log('📁 Archivos recibidos:', newFiles.length);
        console.log('Estado actual de commonCategory:', this.commonCategory);
        
        for (const file of newFiles) {
            // Verificar si ya existe
            const existingFile = this.files.find(f => 
                f.file.name === file.name && 
                f.file.size === file.size &&
                f.file.lastModified === file.lastModified
            );
            
            if (!existingFile) {
                // Validar archivo individual
                if (this.validateSingleFile(file)) {
                    const fileObj = {
                        file: file,
                        id: this.generateFileId(file),
                        status: 'pending',
                        progress: 0,
                        error: null,
                        description: file.name.replace(/\.[^/.]+$/, ""), // Nombre sin extensión
                        customCategory: '',
                        customPersonId: '',
                        customExpirationDate: null,
                        addedAt: new Date().toISOString()
                    };
                    
                    // Si hay categoría común, asignarla
                    if (this.commonCategory && this.commonCategory.trim() !== '') {
                        fileObj.customCategory = this.commonCategory;
                        console.log(`🏷️ Asignando categoría común "${this.commonCategory}" a: ${file.name}`);
                    }
                    
                    this.files.push(fileObj);
                    this.totalSize += file.size;
                    
                    console.log(`✅ Archivo agregado: ${file.name} (${formatFileSize(file.size)})`, {
                        id: fileObj.id,
                        customCategory: fileObj.customCategory,
                        commonCategory: this.commonCategory
                    });
                }
            } else {
                console.log(`⚠️ Archivo duplicado ignorado: ${file.name}`);
            }
        }
        
        console.log(`📊 Estado después de agregar:`, {
            totalArchivos: this.files.length,
            tamañoTotal: formatFileSize(this.totalSize),
            commonCategory: this.commonCategory,
            archivos: this.files.map(f => ({
                nombre: f.file.name,
                categoria: f.customCategory || '(vacía)',
                commonCategory: this.commonCategory
            }))
        });
        console.groupEnd();
        
        return this.files.length;
    }

    /**
     * Elimina un archivo del estado por su ID.
     * @param {string} fileId - ID único del archivo a eliminar
     * @returns {boolean} - True si se eliminó correctamente
     */
    removeFile(fileId) {
        console.log(`🗑️ Intentando eliminar archivo con ID: ${fileId}`);
        const index = this.files.findIndex(f => f.id === fileId);
        if (index !== -1) {
            const removedFile = this.files[index];
            this.totalSize -= removedFile.file.size;
            this.files.splice(index, 1);
            console.log(`✅ Archivo removido: ${removedFile.file.name}`);
            return true;
        }
        console.log(`❌ No se encontró archivo con ID: ${fileId}`);
        return false;
    }

    /**
     * Actualiza la categoría común y la aplica a todos los archivos pendientes
     * @param {string} category - Nueva categoría común
     */
    setCommonCategory(category) {
        console.log(`🏷️ setCommonCategory llamado con: "${category}"`);
        
        const oldCategory = this.commonCategory;
        this.commonCategory = category;
        
        console.log(`📝 Categoría común actualizada: "${oldCategory}" → "${category}"`);
        
        // Aplicar a todos los archivos pendientes sin categoría personalizada
        let updatedCount = 0;
        this.files.forEach(file => {
            if (!file.customCategory && file.status === 'pending') {
                file.customCategory = category;
                updatedCount++;
            }
        });
        
        console.log(`🔄 ${updatedCount} archivos actualizados con categoría común`);
        console.log(`📊 Estado después de setCommonCategory:`, {
            commonCategory: this.commonCategory,
            archivos: this.files.map(f => ({
                nombre: f.file.name,
                categoriaPersonalizada: f.customCategory || '(vacía)',
                status: f.status
            }))
        });
    }

    /**
     * Valida un archivo individual según configuraciones del sistema.
     * Verifica tipo de archivo, tamaño individual y tamaño total acumulado.
     * @param {File} file - Archivo a validar
     * @returns {boolean} - True si el archivo es válido
     */
    validateSingleFile(file) {
        try {
            console.log(`🔍 Validando archivo individual: ${file.name}`);
            
            // Validar tipo de archivo
            const fileExtension = file.name.split('.').pop().toLowerCase();
            if (!CONFIG.ALLOWED_FILE_TYPES.includes(fileExtension)) {
                console.error(`❌ Tipo no permitido: ${fileExtension}`);
                showAlert(
                    `"${file.name}" - Tipo no permitido. Formatos aceptados: ${CONFIG.ALLOWED_FILE_TYPES.join(', ').toUpperCase()}`,
                    'error'
                );
                return false;
            }

            // Validar tamaño individual
            if (file.size > CONFIG.MAX_FILE_SIZE) {
                console.error(`❌ Tamaño excedido: ${formatFileSize(file.size)} > ${formatFileSize(CONFIG.MAX_FILE_SIZE)}`);
                showAlert(
                    `"${file.name}" - Excede el tamaño máximo por archivo (${formatFileSize(CONFIG.MAX_FILE_SIZE)})`,
                    'error'
                );
                return false;
            }

            // Validar tamaño total (si ya hay archivos)
            if (this.totalSize + file.size > CONFIG.MAX_TOTAL_UPLOAD_SIZE) {
                console.error(`❌ Tamaño total excedido`);
                showAlert(
                    `"${file.name}" - Excede el tamaño total permitido para múltiples archivos`,
                    'error'
                );
                return false;
            }

            console.log(`✅ Archivo válido: ${file.name}`);
            return true;

        } catch (error) {
            console.error(`❌ Error validando archivo ${file.name}:`, error);
            showAlert(`Error validando "${file.name}": ${error.message}`, 'error');
            return false;
        }
    }

    /**
     * Valida todos los archivos en el estado globalmente.
     * Verifica límites, categorías y otros requisitos del sistema.
     * @returns {boolean} - True si todos los archivos son válidos
     */
    validateAllFiles() {
        console.group('🔍 validateAllFiles - Validando todos los archivos');
        
        const errors = [];
        
        // Mostrar estado actual para debugging
        console.log('📊 Estado actual para validación:', {
            totalArchivos: this.files.length,
            commonCategory: `"${this.commonCategory}"`,
            archivos: this.files.map((f, i) => ({
                index: i,
                nombre: f.file.name,
                customCategory: `"${f.customCategory}"`,
                status: f.status
            }))
        });
        
        // Verificar límite de archivos
        if (this.files.length > CONFIG.MAX_MULTIPLE_FILES) {
            errors.push(`Máximo ${CONFIG.MAX_MULTIPLE_FILES} archivos permitidos`);
        }

        // Verificar tamaño total
        if (this.totalSize > CONFIG.MAX_TOTAL_UPLOAD_SIZE) {
            errors.push(`Tamaño total excedido (${formatFileSize(this.totalSize)} > ${formatFileSize(CONFIG.MAX_TOTAL_UPLOAD_SIZE)})`);
        }

        // Verificar que haya archivos
        if (this.files.length === 0) {
            errors.push('No hay archivos seleccionados');
            console.error('❌ No hay archivos para validar');
            console.groupEnd();
            return false;
        }

        // VERIFICACIÓN DETALLADA DE CATEGORÍAS
        console.log('🔍 Verificando categorías...');
        
        const hasCommonCategory = this.commonCategory && this.commonCategory.trim() !== '';
        console.log(`🏷️ Tiene categoría común: ${hasCommonCategory} ("${this.commonCategory}")`);
        
        // Contar archivos con categoría personalizada
        const filesWithCustomCategory = this.files.filter(f => 
            f.customCategory && f.customCategory.trim() !== ''
        );
        console.log(`📊 Archivos con categoría personalizada: ${filesWithCustomCategory.length}/${this.files.length}`);
        
        // Identificar archivos sin categoría
        const filesWithoutCategory = this.files.filter(f => 
            !f.customCategory || f.customCategory.trim() === ''
        );
        
        if (filesWithoutCategory.length > 0) {
            console.log('❌ Archivos sin categoría:', filesWithoutCategory.map(f => f.file.name));
            
            if (!hasCommonCategory) {
                errors.push('Debe seleccionar una categoría común para todos los archivos o individualmente');
                console.log('❌ FALLÓ: No hay categoría común y algunos archivos no tienen categoría personalizada');
            } else {
                console.log('✅ Hay categoría común, aplicándola a archivos sin categoría...');
                // Aplicar categoría común a archivos sin categoría
                filesWithoutCategory.forEach(file => {
                    file.customCategory = this.commonCategory;
                    console.log(`🏷️ Aplicando categoría común "${this.commonCategory}" a: ${file.file.name}`);
                });
                
                // Verificar nuevamente después de aplicar
                const stillWithoutCategory = this.files.filter(f => 
                    !f.customCategory || f.customCategory.trim() === ''
                );
                if (stillWithoutCategory.length === 0) {
                    console.log('✅ Todos los archivos ahora tienen categoría');
                } else {
                    console.log('❌ Algunos archivos siguen sin categoría:', stillWithoutCategory.map(f => f.file.name));
                    errors.push('Algunos archivos no tienen categoría asignada');
                }
            }
        } else {
            console.log('✅ Todos los archivos tienen categoría personalizada');
        }

        // Verificar que todas las categorías sean válidas
        const invalidCategories = this.files.filter(f => {
            const cat = this.getEffectiveCategory(f);
            return !cat || cat.trim() === '';
        });
        
        if (invalidCategories.length > 0) {
            errors.push(`${invalidCategories.length} archivo(s) no tienen categoría válida`);
            console.log('❌ Archivos sin categoría válida:', invalidCategories.map(f => f.file.name));
        }

        if (errors.length > 0) {
            console.error('❌ Errores de validación:', errors);
            console.log('📊 Estado final para debugging:', {
                commonCategory: this.commonCategory,
                files: this.files.map(f => ({
                    name: f.file.name,
                    customCategory: f.customCategory,
                    effectiveCategory: this.getEffectiveCategory(f)
                }))
            });
            errors.forEach(error => showAlert(error, 'error'));
            console.groupEnd();
            return false;
        }

        console.log('✅ Validación exitosa - Todos los archivos son válidos');
        console.log('📊 Resumen final:', {
            totalArchivos: this.files.length,
            archivosConCategoria: this.files.filter(f => this.getEffectiveCategory(f)).length,
            categoríaComún: this.commonCategory
        });
        console.groupEnd();
        return true;
    }

    /**
     * Obtiene la categoría efectiva para un archivo específico.
     * Prioriza categoría personalizada sobre categoría común.
     * @param {object} fileObj - Objeto de archivo
     * @returns {string} - Categoría a usar
     */
    getEffectiveCategory(fileObj) {
        // Primero intenta usar la categoría personalizada
        if (fileObj.customCategory && fileObj.customCategory.trim() !== '') {
            return fileObj.customCategory.trim();
        }
        // Si no hay categoría personalizada, usa la común
        if (this.commonCategory && this.commonCategory.trim() !== '') {
            return this.commonCategory.trim();
        }
        // Si no hay ninguna, retorna vacío
        return '';
    }

    /**
     * Prepara los datos de todos los archivos para enviar al servidor.
     * @returns {Array} - Array de objetos preparados para subida
     */
    prepareFilesForUpload() {
        console.group('📤 Preparando archivos para subida');
        
        const preparedFiles = this.files.map(fileObj => {
            const effectiveCategory = this.getEffectiveCategory(fileObj);
            
            console.log(`📋 Preparando: ${fileObj.file.name}`, {
                customCategory: fileObj.customCategory,
                commonCategory: this.commonCategory,
                effectiveCategory: effectiveCategory
            });
            
            return {
                file: fileObj.file,
                fileName: fileObj.file.name,
                fileSize: fileObj.file.size,
                fileType: fileObj.file.type,
                description: fileObj.description || fileObj.file.name.replace(/\.[^/.]+$/, ""),
                category: effectiveCategory,
                personId: fileObj.customPersonId || this.commonPersonId || '',
                expirationDate: fileObj.customExpirationDate || this.expirationDays,
                notifyPerson: this.notifyPerson
            };
        });
        
        console.log('✅ Archivos preparados:', preparedFiles.length);
        console.groupEnd();
        
        return preparedFiles;
    }

    /**
     * Genera un ID único para un archivo basado en nombre, tamaño y timestamp.
     * @param {File} file - Archivo para generar ID
     * @returns {string} - ID único del archivo
     */
    generateFileId(file) {
        return `${file.name}_${file.size}_${file.lastModified}_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
    }

    /**
     * Obtiene estadísticas actuales del estado de subida.
     * @returns {object} - Objeto con conteos de archivos por estado y tamaños
     */
    getStats() {
        return {
            total: this.files.length,
            pending: this.files.filter(f => f.status === 'pending').length,
            uploading: this.files.filter(f => f.status === 'uploading').length,
            completed: this.files.filter(f => f.status === 'completed').length,
            failed: this.files.filter(f => f.status === 'failed').length,
            totalSize: this.totalSize,
            uploadedSize: this.files
                .filter(f => f.status === 'completed')
                .reduce((sum, f) => sum + f.file.size, 0)
        };
    }

    /**
     * Muestra en consola el estado actual de la subida múltiple.
     * Útil para debugging y seguimiento de progreso.
     */
    logState() {
        console.group('📊 Estado de Subida Múltiple - LOG STATE');
        const stats = this.getStats();
        console.table({
            'Total Archivos': stats.total,
            'Pendientes': stats.pending,
            'Subiendo': stats.uploading,
            'Completados': stats.completed,
            'Fallidos': stats.failed,
            'Tamaño Total': formatFileSize(stats.totalSize),
            'Subido': formatFileSize(stats.uploadedSize)
        });
        
        // Mostrar detalles de cada archivo
        this.files.forEach((file, index) => {
            console.log(`${index + 1}. ${file.file.name}`, {
                status: file.status,
                customCategory: file.customCategory || '(vacía)',
                commonCategory: this.commonCategory || '(vacía)',
                effectiveCategory: this.getEffectiveCategory(file) || '(sin categoría)'
            });
        });
        
        console.log('🏷️ Categoría común:', this.commonCategory || '(no establecida)');
        console.groupEnd();
    }

    /**
     * Verifica si todos los archivos tienen categoría
     * @returns {object} - Resultado de la verificación
     */
    checkCategories() {
        const filesWithCategory = this.files.filter(f => 
            this.getEffectiveCategory(f) && this.getEffectiveCategory(f).trim() !== ''
        );
        
        return {
            allHaveCategory: filesWithCategory.length === this.files.length,
            totalFiles: this.files.length,
            filesWithCategory: filesWithCategory.length,
            missingCategories: this.files.length - filesWithCategory.length,
            commonCategory: this.commonCategory,
            details: this.files.map(f => ({
                name: f.file.name,
                hasCategory: !!(this.getEffectiveCategory(f) && this.getEffectiveCategory(f).trim() !== ''),
                customCategory: f.customCategory,
                effectiveCategory: this.getEffectiveCategory(f)
            }))
        };
    }
}